### ISSUE TITLE
CQLAlchemy unable to sync tables

### ISSUE THREAD

**Issue by balazsreho** [domeniconappo/SMFR#1]
When initializing the REST server, it's unable to sync the tables from the models (eg. Tweet), because it tries to compile prepared queries beforehand. As the desired tables do not exists, it fails with the following error message:

```py
   File "/rest_server/start.py", line 59, in <module>
     app = create_app()
   File "/rest_server/start.py", line 28, in create_app
     config.init_cassandra()
   File "/rest_server/server/config.py", line 131, in init_cassandra
     from server.models import Tweet
   File "/rest_server/server/models/__init__.py", line 129, in <module>
     class Tweet(cassandra.Model):
   File "/rest_server/server/models/__init__.py", line 136, in Tweet
     samples_stmt = session.prepare("SELECT * FROM tweet WHERE collectionid=? AND ttype=? ORDER BY tweetid DESC LIMIT ?")
   File "cassandra/cluster.py", line 2369, in cassandra.cluster.Session.prepare
   File "cassandra/cluster.py", line 2366, in cassandra.cluster.Session.prepare
   File "cassandra/cluster.py", line 4026, in cassandra.cluster.ResponseFuture.result
 cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table tweet"
```

The corresponding code from models:

```py
  samples_stmt = session.prepare("SELECT * FROM tweet WHERE collectionid=? AND ttype=? ORDER BY tweetid DESC LIMIT ?")
  stmt = session.prepare("SELECT * FROM tweet WHERE collectionid=? AND ttype=? ORDER BY tweetid DESC")
  stmt_with_lang = session.prepare("SELECT * FROM tweet WHERE collectionid=? AND ttype=? AND lang=?")
```

Because of it, MySQL migrations fail too (as the whole server shuts down, because of the non-existent Cassandra tables)

I'll try to modify the models __init__ file, to overcome this issue, but we need to refactor the prepared statements location, to overcome this problem in the future.

**Comment by domeniconappo** [comment]
@balazsreho 
Just to overcome temporary the issue, could you try to comment that code which is defining and using those prepared statements, start up the servers with docker-compose up -d (this will properly init Cassandra keyspaces and column families...), then stop all the services again and uncomment the code back. 
In this way the issue should 'disappear'...it's a dirty trick but if you want to start working soon it can be useful.

Another option is to copy the whole cassandra data directory from contabo server (from /DATA/smfr/data/cassandra, ~4 GB) so you can start from a populated cassandra keyspace.

**Comment by balazsreho** [comment]
@domeniconappo 
I've tried it, and it works flawlessly! For the sake of safety, here are the steps:

1. Stop all previous docker-compose containers,
2. Comment out the 3 line, with prepared statements
3. Rebuild the restserver with `docker-compose build`
4. Start all services. The restserver will fail because of the non-existent MySQL tables (we couldn't migrate, because of the error)
5. Run `flask db migrate` (exec, or bash in to the container and run manually)
6. Stop all services
7. Uncomment the 3 lines
8. Rebuild, and run the services

Now everything is accessible, and running. I think moving the prepared statements to a new function, which will only be called if the server is not bootstrapping should be fine. I'll test it, and make a merge request if it works.

**Comment by domeniconappo** [comment]
@balazsreho 
Great. Thanks for testing! Solution you've proposed should do the trick.

Just one small note to avoid future confusion: the command to init/upgrade the db mysql is `flask db upgrade` (it runs the migrations files under https://github.com/domeniconappo/SMFR/tree/master/rest_server/src/migrations/versions folder to sync between models and the db) while `flask db migrate` creates new migrations files that must be added and pushed to GIT. You should run this command in case you have new mysql models or you've added/dropped fields of an existing model/table.

The README is still quite chaotic...I will do my best to write clear instructions within the end of the week.
